### ISSUE TITLE
Vercel deployment gives error

### ISSUE THREAD

**Issue by ask4jm** [timotejroiko/sweph#22]
Anyy clues!! Thanks

Error: Cannot find module './build/Release/sweph.node'
Require stack:
- /vercel/path0/node_modules/sweph/index.mjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at /var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:11:28979
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at /opt/rust/nodejs.js:1:11506
    at Function.Xt (/opt/rust/nodejs.js:1:11878)
    at Z.e.<computed>.X._load (/opt/rust/nodejs.js:1:11476)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at u.require (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:11:29195)
    at require (node:internal/modules/helpers:179:18)
    at 36066 (/var/task/.next/server/app/api/test/route.js:1:631) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/vercel/path0/node_modules/sweph/index.mjs' ],
  page: '/api/test'
}

**Comment by timotejroiko** [comment]
i have never used vercel/nextjs so i cannot test, but try looking at this:

https://github.com/eisberg-labs/nextjs-node-loader  
https://github.com/eisberg-labs/nextjs-node-loader/tree/main/examples/next-14-el-slugify

**Comment by CagatayUlubay** [comment]
I am using Netlify and have the same error.

I already included nextjs node loader:
`config.module.rules.push({
      test: /\.node$/,
      use: [
        {
          loader: "nextjs-node-loader",
        },
      ],
    });`

Sadly I still get the error:
![image](https://github.com/user-attachments/assets/5516665c-2b0d-45a6-b043-72ed1d4395e1)

**Comment by timotejroiko** [comment]
I just tested vercel myself, and it worked without issue using vercel functions.

I created a project using [vercel nodejs serverless functions template](https://vercel.com/templates/backend/nodejs-serverless-function-express), using node.js v22, no extra configuration.

This is the code: [sweph-vercel-example](https://github.com/timotejroiko/sweph-vercel-example)

**Comment by timotejroiko** [comment]
closing this, feel free to reopen if needed
